package com.example.myapp;

import com.codename1.system.Lifecycle;
import com.codename1.ui.Toolbar;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
//./run.sh
public class MyApp extends Lifecycle {
    @Override //entry point 
    public void runApp() {
        Game.game = Game.getGame();
        Game.game.startGameThread();
        init(getClass());
    }
        @Override
        public void init(Object context) {
            Toolbar.setGlobalToolbar(false);
        }

}
